name: Bu2g report
description: Create a bug report if there is something not working
title: "bug: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      placeholder: Please describe the bug encountered.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: How to Reproduce
      placeholder: Please provide a list of steps to reproduce the bug.
    validations:
      required: true
  - type: input
    id: kernel
    attributes:
      label: Kernel Version
      placeholder: Please provide the output of `uname -a`
    validations:
      required: true
  - type: input
    id: model
    attributes:
      label: SBC Model
      placeholder: Please provide the output `cat /proc/device-tree/model`
    validations:
      required: true
  - type: dropdown
    id: ubuntu
    attributes:
      label: Ubuntu Version
      multiple: false
      options:
        - Ubuntu 22.04 LTS (Jammy Jellyfish)
        - Ubuntu 24.04 LTS (Noble Nombat)
    validations:
      required: true
